.PHONY: dev test doc

dev:
	uvicorn app.main:app --reload --port 8000  --reload-dir app --host=0.0.0.0

# 用默认浏览器打开文档页面
	
doc:
	@echo "Opening http://0.0.0.0:8000/docs ..."
	@python -c "import webbrowser; webbrowser.open('http://0.0.0.0:8000/docs')"

test:
	pytest -q